### ISSUE TITLE
ttf2woff2\jssrc\ttf2woff2.js:1 Error  at new JS_Parse_Error (eval at <anonymous>

### ISSUE THREAD

**Issue by sumaolin** [sumaolin/generator-kmapp#2]
#1 解决后，出现的新问题：`gulp build`时候报错：
```
D:\svn\demo_test\youge\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filen
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (D:\svn\demo_test\youge\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2904:23)
```
反复修改了gulpfile配置，是因为`$.uglify() `和 `cleanCSS()`引起的，根据错误信息想到是没有符合条件的stream ，先怀疑是gulp-useref引起的，升级版本配置后问题依然存在，只好回退回来，后面判断是不是gulp-if 引起的的啊，升级到最新版本2.0.2后解决了

**Comment by sumaolin** [comment]
初步的想法是因为：node 或者 npm 版本导致的问题，最近升级到 `node 6.10.3' `npm 4.0.3'引起的package不兼容
